// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	danmv1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeReservedIPs implements ReservedIPInterface
type fakeReservedIPs struct {
	*gentype.FakeClientWithList[*v1.ReservedIP, *v1.ReservedIPList]
	Fake *FakeDanmV1
}

func newFakeReservedIPs(fake *FakeDanmV1, namespace string) danmv1.ReservedIPInterface {
	return &fakeReservedIPs{
		gentype.NewFakeClientWithList[*v1.ReservedIP, *v1.ReservedIPList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("reservedips"),
			v1.SchemeGroupVersion.WithKind("ReservedIP"),
			func() *v1.ReservedIP { return &v1.ReservedIP{} },
			func() *v1.ReservedIPList { return &v1.ReservedIPList{} },
			func(dst, src *v1.ReservedIPList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ReservedIPList) []*v1.ReservedIP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ReservedIPList, items []*v1.ReservedIP) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
