// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ReservedIPsGetter has a method to return a ReservedIPInterface.
// A group's client should implement this interface.
type ReservedIPsGetter interface {
	ReservedIPs(namespace string) ReservedIPInterface
}

// ReservedIPInterface has methods to work with ReservedIP resources.
type ReservedIPInterface interface {
	Create(ctx context.Context, reservedIP *danmv1.ReservedIP, opts metav1.CreateOptions) (*danmv1.ReservedIP, error)
	Update(ctx context.Context, reservedIP *danmv1.ReservedIP, opts metav1.UpdateOptions) (*danmv1.ReservedIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, reservedIP *danmv1.ReservedIP, opts metav1.UpdateOptions) (*danmv1.ReservedIP, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*danmv1.ReservedIP, error)
	List(ctx context.Context, opts metav1.ListOptions) (*danmv1.ReservedIPList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *danmv1.ReservedIP, err error)
	ReservedIPExpansion
}

// reservedIPs implements ReservedIPInterface
type reservedIPs struct {
	*gentype.ClientWithList[*danmv1.ReservedIP, *danmv1.ReservedIPList]
}

// newReservedIPs returns a ReservedIPs
func newReservedIPs(c *DanmV1Client, namespace string) *reservedIPs {
	return &reservedIPs{
		gentype.NewClientWithList[*danmv1.ReservedIP, *danmv1.ReservedIPList](
			"reservedips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *danmv1.ReservedIP { return &danmv1.ReservedIP{} },
			func() *danmv1.ReservedIPList { return &danmv1.ReservedIPList{} },
		),
	}
}
