// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ReservedIPLister helps list ReservedIPs.
// All objects returned here must be treated as read-only.
type ReservedIPLister interface {
	// List lists all ReservedIPs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.ReservedIP, err error)
	// ReservedIPs returns an object that can list and get ReservedIPs.
	ReservedIPs(namespace string) ReservedIPNamespaceLister
	ReservedIPListerExpansion
}

// reservedIPLister implements the ReservedIPLister interface.
type reservedIPLister struct {
	listers.ResourceIndexer[*danmv1.ReservedIP]
}

// NewReservedIPLister returns a new ReservedIPLister.
func NewReservedIPLister(indexer cache.Indexer) ReservedIPLister {
	return &reservedIPLister{listers.New[*danmv1.ReservedIP](indexer, danmv1.Resource("reservedip"))}
}

// ReservedIPs returns an object that can list and get ReservedIPs.
func (s *reservedIPLister) ReservedIPs(namespace string) ReservedIPNamespaceLister {
	return reservedIPNamespaceLister{listers.NewNamespaced[*danmv1.ReservedIP](s.ResourceIndexer, namespace)}
}

// ReservedIPNamespaceLister helps list and get ReservedIPs.
// All objects returned here must be treated as read-only.
type ReservedIPNamespaceLister interface {
	// List lists all ReservedIPs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.ReservedIP, err error)
	// Get retrieves the ReservedIP from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*danmv1.ReservedIP, error)
	ReservedIPNamespaceListerExpansion
}

// reservedIPNamespaceLister implements the ReservedIPNamespaceLister
// interface.
type reservedIPNamespaceLister struct {
	listers.ResourceIndexer[*danmv1.ReservedIP]
}
